kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo hello
  - echo world
- name: docker  
  image: plugins/docker
  settings:
    repo: registry.digitalocean.com/ur-du-kuga/test-drone